name: Main Branch CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v4.7.1
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvn clean install
