apiVersion: v1
data:
  CONFIG_SERVER_HOST: config-server
  CONFIG_SERVER_PORT: '8888'
  SPRING_CONFIG_IMPORT: configserver:http://config-server:8888/
  SPRING_PROFILES_ACTIVE: kubernetes
kind: ConfigMap
metadata:
  name: shared-config
  namespace: retailstore
