apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: retailstore
spec:
  ports:
  - port: 18282
    targetPort: 18282
    name: http
  - name: jobrunr
    port: 28282
    targetPort: 28282
  selector:
    app: order-service
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: retailstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - env:
        - name: CONFIG_SERVER_USR
          valueFrom:
            secretKeyRef:
              key: CONFIG_SERVER_USR
              name: config-server-credentials
        - name: CONFIG_SERVER_PWD
          valueFrom:
            secretKeyRef:
              key: CONFIG_SERVER_PWD
              name: config-server-credentials
        - name: SPRING_CONFIG_IMPORT
          value: 
            optional:configserver:http://$(CONFIG_SERVER_USR):$(CONFIG_SERVER_PWD)@config-server:8888/
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgresql:5432/appdb
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: postgres-credentials
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: postgres-credentials
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: http://service-registry:8761/eureka/
        - name: APPLICATION_CATALOG_SERVICE_URL
          value: http://catalog-service:18080/catalog-service
        envFrom:
        - configMapRef:
            name: shared-config
        image: dockertmt/mmv2-order-service:0.0.1-SNAPSHOT
        livenessProbe:
          httpGet:
            path: /order-service/actuator/health/liveness
            port: 18282
          initialDelaySeconds: 5
          periodSeconds: 10
        name: order-service
        ports:
        - containerPort: 18282
        - containerPort: 28282
        readinessProbe:
          httpGet:
            path: /order-service/actuator/health/readiness
            port: 18282
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            memory: 1400Mi
            cpu: 1000m
          requests:
            memory: 512Mi
            cpu: 200m
        startupProbe:
          failureThreshold: 30
          httpGet:
            path: /order-service/actuator/health/liveness
            port: 18282
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      initContainers:
      - command:
        - sh
        - -c
        - 'until nc -z config-server 8888; do echo waiting for config-server; sleep
          2; done;

          until nc -z service-registry 8761; do echo waiting for service-registry;
          sleep 2; done;

          until nc -z postgresql 5432; do echo waiting for postgresql; sleep 2; done;

          until nc -z kafka 9092; do echo waiting for kafka; sleep 2; done;

          '
        image: busybox:1.36
        name: wait-for-dependencies
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
      serviceAccountName: order-service
      volumes:
      - name: tmp-volume
        emptyDir: {}
