apiVersion: v1
kind: Secret
metadata:
  name: config-server-credentials
  namespace: retailstore
stringData:
  CONFIG_SERVER_PWD: dev-pass
  CONFIG_SERVER_USR: dev-usr
  SPRING_CLOUD_CONFIG_PASSWORD: dev-pass
  SPRING_CLOUD_CONFIG_USERNAME: dev-usr
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
  namespace: retailstore
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin1234
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: retailstore
stringData:
  POSTGRES_PASSWORD: secret
  POSTGRES_USER: appuser
  username: appuser
  password: secret
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: webapp-oauth2-credentials
  namespace: retailstore
stringData:
  OAUTH2_CLIENT_SECRET: P1sibsIrELBhmvK18BOzw1bUl96DcP2z
type: Opaque
