route:
  receiver: 'default-receiver'
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  routes:
    - matchers:
        - severity="critical"
      receiver: 'critical-alerts'
    - matchers:
        - severity="warning"
      receiver: 'warning-alerts'

receivers:
  - name: 'default-receiver'
  - name: 'critical-alerts'
    email_configs:
      - to: 'placeholder@gmail.com'
        from: 'no-reply-retail@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'username'
        auth_password: 'password'
        require_tls: true
        html: '{{ template "email.default.html" . }}<br>Runbook: {{ range .Alerts }}{{ .Annotations.runbook_url }}<br>{{ end }}'
  - name: 'warning-alerts'
    email_configs:
      - to: 'placeholder@gmail.com'
        from: 'no-reply-retail@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'username'
        auth_password: 'password'
        require_tls: true
        html: '{{ template "email.default.html" . }}<br>Runbook: {{ range .Alerts }}{{ .Annotations.runbook_url }}<br>{{ end }}'
