{
 "title": "Logs, Traces, Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "PAYMENT-SERVICE-LOGS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"payment-service\"} |= ``"
    }
   ]
  },
  {
   "title": "CATALOG-SERVICE-LOGS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"catalog-service\"} |= ``"
    }
   ]
  },
  {
   "title": "ORDER-SERVICE-LOGS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"order-service\"} |= ``"
    }
   ]
  },
  {
   "title": "API-GATEWAY-LOGS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"api-gateway\"} |= ``"
    }
   ]
  },
  {
   "title": "INVENTORY-SERVICE-LOGS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container=\"inventory-service\"} |= ``"
    }
   ]
  },
  {
   "title": "CONFIG-SERVER-LOGS",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "{container=\"config-server\"} |= ``"
    }
   ]
  },
  {
   "title": "latency for All",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(1.00, sum(rate(http_server_requests_seconds_bucket{uri=~\".*\"}[$__rate_interval])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{uri=~\".*\"}[$__rate_interval])) by (le))",
     "legendFormat": "tp99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{uri=~\".*\"}[$__rate_interval])) by (le))",
     "legendFormat": "tp95"
    }
   ]
  }
 ]
}