apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: staging-secret-store
spec:
  provider:
    fake:
      data:
        - key: /staging/retailstore/config-server-credentials
          valueMap:
            CONFIG_SERVER_PWD: "staging-config-pass"
            CONFIG_SERVER_USR: "staging-usr"
            SPRING_CLOUD_CONFIG_PASSWORD: "staging-config-pass"
            SPRING_CLOUD_CONFIG_USERNAME: "staging-usr"
        - key: /staging/retailstore/keycloak-admin-credentials
          valueMap:
            KEYCLOAK_ADMIN: "admin"
            KEYCLOAK_ADMIN_PASSWORD: "staging-kc-pass"
        - key: /staging/retailstore/postgres-credentials
          valueMap:
            POSTGRES_PASSWORD: "staging-pg-pass"
            POSTGRES_USER: "appuser"
            username: "appuser"
            password: "staging-pg-pass"
        - key: /staging/retailstore/webapp-oauth2-credentials
          valueMap:
            OAUTH2_CLIENT_SECRET: "staging-oauth-secret"
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: config-server-credentials
  namespace: retailstore
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: staging-secret-store
    kind: ClusterSecretStore
  target:
    name: config-server-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: /staging/retailstore/config-server-credentials
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keycloak-admin-credentials
  namespace: retailstore
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: staging-secret-store
    kind: ClusterSecretStore
  target:
    name: keycloak-admin-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: /staging/retailstore/keycloak-admin-credentials
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-credentials
  namespace: retailstore
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: staging-secret-store
    kind: ClusterSecretStore
  target:
    name: postgres-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: /staging/retailstore/postgres-credentials
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webapp-oauth2-credentials
  namespace: retailstore
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: staging-secret-store
    kind: ClusterSecretStore
  target:
    name: webapp-oauth2-credentials
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: /staging/retailstore/webapp-oauth2-credentials
