global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['host.docker.internal:9090']
        labels:
          application: 'prometheus'
  - job_name: 'otel-collector'
    scrape_interval: 2s
    static_configs:
      - targets: [ 'otel-collector:8889' ]
        labels:
          application: 'otel-collector'
  - job_name: 'keycloak'
    scrape_interval: 2s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'keycloak:9000' ]
        labels:
          application: 'keycloak'

rule_files:
  - 'alert-rules.yml'

alerting:
  alertmanagers:
    - scheme: http
    - static_configs:
        - targets: ['host.docker.internal:9093']