apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store-webapp
  namespace: retailstore
spec:
  template:
    spec:
      hostAliases:
      - ip: "10.43.228.239"
        hostnames:
        - "keycloak.local"
