spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/appdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  kafka:
    bootstrap-servers: kafka:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    preferIpAddress: true
