resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignoreExceptions:
          - com.example.catalogservice.exception.ProductNotFoundException
      shared:
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 30
        waitDurationInOpenState: 1s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        ignoreExceptions:
          - com.example.catalogservice.exception.ProductNotFoundException
    instances:
      default:
        baseConfig: default
      getInventoryByProductCodes:
        baseConfig: shared
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 100
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignoreExceptions:
          - com.example.catalogservice.exception.ProductNotFoundException
    instances:
      default:
        baseConfig: default
      getInventoryByProductCodes:
        baseConfig: default
  bulkhead:
    configs:
      default:
        maxConcurrentCalls: 100
    instances:
      default:
        maxConcurrentCalls: 10
      getInventoryByProductCodes:
        maxWaitDuration: 10ms
        maxConcurrentCalls: 20
  thread-pool-bulkhead:
    configs:
      default:
        maxThreadPoolSize: 4
        coreThreadPoolSize: 2
        queueCapacity: 2
    instances:
      default:
        baseConfig: default
      getInventoryByProductCodes:
        maxThreadPoolSize: 1
        coreThreadPoolSize: 1
        queueCapacity: 1
  ratelimiter:
    configs:
      default:
        registerHealthIndicator: false
        limitForPeriod: 100
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        eventConsumerBufferSize: 100
    instances:
      default:
        baseConfig: default
      getInventoryByProductCodes:
        limitForPeriod: 6
        limitRefreshPeriod: 500ms
        timeoutDuration: 3s
  timelimiter:
    configs:
      default:
        cancelRunningFuture: false
        timeoutDuration: 2s
    instances:
      default:
        baseConfig: default
      getInventoryByProductCodes:
        baseConfig: default

spring:
  webflux:
    problemdetails:
      enabled: true
management:
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
