application.order-service-url=lb://order-service/order-service

management.health.circuitbreakers.enabled=true
management.health.ratelimiters.enabled=true

resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=10
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10000
resilience4j.circuitbreaker.configs.default.failureRateThreshold=60
resilience4j.circuitbreaker.configs.default.eventConsumerBufferSize=10
resilience4j.circuitbreaker.instances.default.failureRateThreshold=90

application.byPassCircuitBreaker=false
