server:
  port: 18181
  servlet:
    contextPath: /${spring.application.name}
spring:
  application:
    name: inventory-service
  testcontainers:
    beans:
      startup: parallel
  kafka:
# bootstrap-servers: 127.0.0.1:9092
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
            value.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
          json:
            trusted:
              packages: "com.example.common.dtos"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: true
  threads:
    virtual:
      enabled: true
  http:
      clients.imperative.factory: jdk
  main:
    web-application-type: servlet