apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: add
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: IfNotPresent
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1400Mi"
      - op: add
        path: /spec/template/spec/dnsConfig
        value:
          options:
            - name: single-request-reopen
            - name: ndots
              value: "2"
  - target:
      kind: Deployment
      name: keycloak
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1400Mi"
  - target:
      kind: Deployment
      name: "^(api-gateway|catalog-service|config-server|inventory-service|order-service|payment-service|retail-store-webapp|service-registry|keycloak)$"
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: JDK_JAVA_OPTIONS
          value: "-Djava.net.preferIPv4Stack=true"

images:
  - name: dockertmt/mmv2-config-server
    newTag: "0.0.1-SNAPSHOT"
  - name: dockertmt/mmv2-service-registry-25
    newTag: "0.0.1-SNAPSHOT"
  - name: dockertmt/mmv2-api-gateway
    newTag: "0.0.1-SNAPSHOT"
  - name: dockertmt/mmv2-catalog-service
    newTag: "0.0.1-SNAPSHOT"
  - name: dockertmt/mmv2-inventory-service
    newTag: "0.0.1-SNAPSHOT"
  - name: dockertmt/mmv2-order-service
    newTag: "0.0.1-SNAPSHOT"
  - name: dockertmt/mmv2-payment-service
    newTag: "0.0.1-SNAPSHOT"
  - name: dockertmt/mmv2-retail-store-webapp
    newTag: "0.0.1-SNAPSHOT"
