apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-service-scaler
  namespace: retailstore
spec:
  scaleTargetRef:
    name: order-service
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka.retailstore.svc.cluster.local:9092
      consumerGroup: order-service
      topic: payment-orders
      lagThreshold: "10"
  - type: kafka
    metadata:
      bootstrapServers: kafka.retailstore.svc.cluster.local:9092
      consumerGroup: order-service
      topic: stock-orders
      lagThreshold: "10"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: payment-service-scaler
  namespace: retailstore
spec:
  scaleTargetRef:
    name: payment-service
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka.retailstore.svc.cluster.local:9092
      consumerGroup: payment
      topic: orders
      lagThreshold: "10"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: inventory-service-scaler
  namespace: retailstore
spec:
  scaleTargetRef:
    name: inventory-service
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
  - type: kafka
    metadata:
      bootstrapServers: kafka.retailstore.svc.cluster.local:9092
      consumerGroup: stock
      topic: orders
      lagThreshold: "10"
