server:
  http_listen_port: 3100
  http_listen_address: 0.0.0.0
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
        http:
    jaeger:
      protocols:
        thrift_http:
        grpc:
        thrift_binary:
        thrift_compact:
    zipkin:
      endpoint: 0.0.0.0:9411

ingester:
  trace_idle_period: 10s
  max_block_bytes: 1_000_000
  max_block_duration: 5m

querier:
  search:
    query_timeout: 30s

metrics_generator:
  registry:
    external_labels:
      source: tempo
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://host.docker.internal:9090/api/v1/write
        send_exemplars: true
  traces_storage:
    path: /tmp/tempo/generator/traces
  processor:
    local_blocks:
      flush_to_storage: true
      filter_server_spans: false

query_frontend:
  metrics:
    concurrent_jobs: 8
    target_bytes_per_job: 1.25e+09
    max_duration: 3h

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks

overrides:
  metrics_generator_processors: [service-graphs, span-metrics, local-blocks]

usage_report:
  reporting_enabled: false
