name: Test Docker Compose Tools Upgrade

on:
  push:
    paths:
      - 'docker-compose-tools.yml'
  pull_request:
    paths:
      - 'docker-compose-tools.yml'

jobs:
  test-tools-upgrade:
    uses: ./.github/workflows/end-to-end-tests.yml
    with:
      command_args: 'setup teardown'
